version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3002
      - ORDER_SERVICE_URL=http://order-processing-service:3001
      - STOCK_SERVICE_URL=http://stock-management-service:3003
    depends_on:
      - auth-service
      - order-processing-service
      - stock-management-service

  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - JWT_EXPIRATION=1h
      - MONGODB_URI=mongodb://mongodb:27017/auth_db
    depends_on:
      - mongodb

  order-processing-service:
    build: ./order-processing-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/order_db
      - STOCK_SERVICE_URL=http://stock-management-service:3003/api/stock
    depends_on:
      - mongodb
      - stock-management-service

  stock-management-service:
    build: ./stock-management-service
    ports:
      - "3003:3003"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=flipzon

volumes:
  redis-data:
  mongodb-data: