version: '3.8'

services:
  stock-management-service:
    build: ./stock-management-service
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  order-processing-service:
    build: ./order-processing-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/flipzon
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STOCK_SERVICE_URL=http://stock-management-service:3000/api/stock
    depends_on:
      - mongodb
      - redis
      - stock-management-service

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=flipzon

volumes:
  redis-data:
  mongodb-data: