apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: flash-sale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: your-registry/auth-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          value: "1h"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/auth_db"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: flash-sale
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002