apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-management
  namespace: flash-sale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-management
  template:
    metadata:
      labels:
        app: stock-management
    spec:
      containers:
      - name: stock-management
        image: your-registry/stock-management:latest
        ports:
        - containerPort: 3003
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: stock-management-service
  namespace: flash-sale
spec:
  selector:
    app: stock-management
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003